Category task
DmitryLazyuka/spring-project pull request #10
Opened 2024-08-24 20:33 UTC by DmitryLazyuka

2024-08-25 17:54 UTC, Elena-Bruyako requested changes
see comments

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/controller/BookController.java
> +
```suggestion
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/model/Book.java
> +            name = "book_category",
```suggestion
            name = "books_categories",
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/model/Category.java
> +    public Category() {
use Lombok annotation

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/repository/category/CategoryRepository.java
> +
```suggestion
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/CategoryService.java
> +
```suggestion
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/BookServiceImpl.java
> +        if (!hasValidCategories(requestDto)) {
```suggestion
        Book book = bookMapper.toBook(bookDto);
        book.setCategories(categoriesIdToCategories(bookDto.categoriesId()));
        return bookMapper.toDto(bookRepository.save(book));
```

where

```
private Set<Category> categoriesIdToCategories(List<Long> categories) {
        return categories.stream()
                .map(categoryRepository::getReferenceById)
                .collect(Collectors.toSet());
    }
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/CategoryServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new NoSuchElementException(
```suggestion
                .orElseThrow(() -> new EntityNotFoundException(
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new NoSuchElementException(
```suggestion
                .orElseThrow(() -> new EntityNotFoundException(
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/CategoryServiceImpl.java
> +    public Category getCategoryById(Long id) {
what the difference between this method and getById ?

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(updatedCategory);
```suggestion
        Category category = repository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(
                        "No such a category with id: " + id
                ));
        mapper.updateCategoryFromDto(categoryDto, category);
        return mapper.toDto(repository.save(category));
```

2024-08-25 17:54 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/repository/category/CategoryRepository.java
> +    long countByIds(@Param("ids") Set<Long> ids);
remove

2024-08-26 13:26 UTC, Elena-Bruyako requested changes
see comments

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/controller/BookController.java
> +    private final CategoryRepository categoryRepository;
unused

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(SQLIntegrityConstraintViolationException.class)
unused exception

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/dto/book/CreateBookRequestDto.java
> +    private Set<Long> categoryIds;
```suggestion
    @NotEmpty
    private Set<Long> categoryIds;
```

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/mapper/BookMapper.java
> +        if (requestDto.getCategoryIds() != null) {
```suggestion
```

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/mapper/CategoryMapper.java
> +
```suggestion
```

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/mapper/UserMapper.java
> +
```suggestion
```

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/CategoryService.java
> +
not fixed
 don't begin class or method with empty line

2024-08-26 13:26 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/BookServiceImpl.java
> +
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(getNotFoundMessage(id)));
        bookMapper.updateBookFromDto(bookDto, book);
        book.setCategories(categoriesIdToCategories(bookDto.categoriesId()));
        return bookMapper.toDto(bookRepository.save(book));
```

2024-08-28 12:24 UTC, Elena-Bruyako requested changes
see comments

2024-08-28 12:24 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/controller/CategoryController.java
> +@RestController
```suggestion
@RestController
@Validated
```

as you use `@Positive` for Long id

2024-08-28 12:24 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/BookServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-08-28 19:47 UTC, sarakhmen approved these changes

2024-08-29 07:11 UTC, merged