Added Order Functionality
DmitryLazyuka/spring-project pull request #12
Opened 2024-09-28 14:59 UTC by DmitryLazyuka

2024-09-29 17:36 UTC, Elena-Bruyako requested changes
see comments

2024-09-29 17:36 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/controller/OrderController.java
> +    OrderDto updateOrderStatus(@RequestBody StatusUpdateRequestDto request,
```suggestion
    public OrderDto updateOrderStatus(@RequestBody StatusUpdateRequestDto request,
```

2024-09-29 17:36 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/controller/OrderController.java
> +        return orderService.updateOrderStatus(orderId, request);
rename request

2024-09-29 17:36 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/OrderServiceImpl.java
> +        return orders.stream().map(orderMapper::toDto).toList();
```suggestion
        return orders.stream()
        .map(orderMapper::toDto)
        .toList();
```

2024-09-29 17:36 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/OrderServiceImpl.java
> +            throw new IllegalStateException("Cart is empty or not available");
```suggestion
            throw new OrderProcessingException("Cart is empty or not available");
```

2024-09-29 17:36 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/OrderServiceImpl.java
> +                .orElseThrow(() -> new NoSuchElementException("Order with " + orderId
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Order with " + orderId
```

check other places and fix

2024-09-29 17:36 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/service/impl/OrderServiceImpl.java
> +        return order.getOrderItems().stream().map(orderMapper::toOrderItemDto).toList();
```suggestion
        return order.getOrderItems()
        .stream()
        .map(orderMapper::toOrderItemDto)
        .toList();
```

2024-10-02 14:33 UTC, Elena-Bruyako requested changes
see comments

2024-10-02 14:33 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
wrong status

2024-10-02 14:33 UTC, Elena-Bruyako commented on src/main/java/org/example/springproject/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(NoSuchElementException.class)
Do you need this exception? Of it's the same as EntityNotFoundException, leave only one

2024-10-06 14:46 UTC, sarakhmen approved these changes

2024-10-07 15:45 UTC, merged